import test from 'node:test';import assert from 'node:assert/strict';import {build} from 'esbuild';
const {outputFiles}=await build({entryPoints:['supabase/functions/market-data/providers.ts'],bundle:true,format:'esm',platform:'node',write:false});const p=await import('data:text/javascript;base64,'+Buffer.from(outputFiles[0].text).toString('base64'));
const now=Math.floor(Date.now()/1000);
test('crypto IDR and provider timestamp are preserved',()=>{const q=p.parseCoin({idr:100,last_updated_at:now});assert.equal(q.price_idr,100);assert.equal(q.as_of,new Date(now*1000).toISOString());assert.throws(()=>p.parseCoin({idr:0,last_updated_at:now}));assert.throws(()=>p.parseCoin({idr:100}));assert.throws(()=>p.parseCoin({idr:100,last_updated_at:now+10000}));});
test('US quote converts through timestamped FX and rejects wrong instrument',()=>{const a={id:'x',provider:'twelve',provider_id:'ACWI',exchange:'NASDAQ',currency:'USD'};const row={symbol:'ACWI',exchange:'NASDAQ',currency:'USD',close:'150',timestamp:now,is_market_open:false};const q=p.parseTwelve(row,{rate:16000,timestamp:now},a);assert.equal(q.price_idr,2400000);assert.equal(q.market_open,false);assert.throws(()=>p.parseTwelve({...row,currency:'EUR'},{rate:1,timestamp:now},a));assert.throws(()=>p.parseTwelve({...row,symbol:'OTHER'},{rate:1,timestamp:now},a));assert.throws(()=>p.parseTwelve(row,{rate:16000},a));});
test('IDX explicitly marked EOD; provider errors never become zero',()=>{const a={id:'x',provider:'twelve',provider_id:'PACK',exchange:'IDX',currency:'IDR'};assert.equal(p.parseTwelve({symbol:'PACK',exchange:'IDX',currency:'IDR',close:560,timestamp:now},null,a).status,'eod');assert.throws(()=>p.parseTwelve({status:'error',code:403},null,a));});
test('custom feed rejects mismatched ID and unlabelled latency',()=>{assert.throws(()=>p.parseCustom({id:'wrong',price_idr:10,as_of:new Date().toISOString(),status:'nav',source:'test'},'right'));assert.throws(()=>p.parseCustom({id:'right',price_idr:10,as_of:new Date().toISOString(),source:'test'},'right'));});
test('cache invalidation follows provider mapping and timestamp',()=>{const a={id:'x',provider:'coingecko',provider_id:'bitcoin',exchange:'',currency:'IDR'};const q={mapping_key:p.mappingKey(a),fetched_at:new Date().toISOString()};assert.equal(p.isDue(q,a),false);assert.equal(p.isDue(q,{...a,provider_id:'ethereum'}),true);assert.equal(p.isDue({...q,fetched_at:'2000-01-01'},a),true);});
test('provider timeout/errors use generic error and reject non-json',async()=>{await assert.rejects(()=>p.fetchJson('https://example.test',{},async()=>new Response('{}',{status:429})),/Batas API/);await assert.rejects(()=>p.fetchJson('https://example.test',{},async()=>new Response('not json')));});
