import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {PGlite} from '@electric-sql/pglite';
const admin='11111111-1111-4111-8111-111111111111',editor='22222222-2222-4222-8222-222222222222',viewer='33333333-3333-4333-8333-333333333333',pending='44444444-4444-4444-8444-444444444444';
const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz,raw_user_meta_data jsonb);create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;grant usage on schema auth to authenticated,anon,service_role;grant execute on function auth.uid() to authenticated,anon,service_role;`);
await db.exec(fs.readFileSync('supabase/migrations/202609260001_arbor.sql','utf8'));
for(const [id,role] of [[admin,'admin'],[editor,'editor'],[viewer,'viewer'],[pending,'pending']]){await db.query('insert into auth.users values($1,$2,now(),$3)',[id,role+'@example.com',JSON.stringify({role:'admin'})]);if(role!=='pending')await db.query('update memberships set role=$1 where user_id=$2',[role,id]);}
async function asUser(id,sql,args=[]){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role authenticated');try{return await db.query(sql,args)}finally{await db.exec('reset role')}}
const asset={id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',symbol:'TEST',name:'Test asset',category:'Test',broker:'Test',qty:2,cost:100,provider:'manual',provider_id:'',exchange:'',currency:'IDR',note:'',manual_price:60,manual_as_of:'2026-01-01T00:00:00Z'};
test('signup metadata cannot grant admin; pending cannot read holdings',async()=>{const r=await asUser(pending,'select * from memberships');assert.equal(r.rows.length,1);assert.equal(r.rows[0].role,'pending');assert.equal((await asUser(pending,'select * from assets')).rows.length,0);await assert.rejects(()=>asUser(pending,"update memberships set role='admin'"));await assert.rejects(()=>asUser(pending,'select save_asset($1,null)',[JSON.stringify(asset)]));});
test('editor writes via RPC, viewer cannot write or approve',async()=>{await asUser(editor,'select save_asset($1,null)',[JSON.stringify(asset)]);assert.equal((await asUser(viewer,'select * from assets')).rows.length,1);await assert.rejects(()=>asUser(viewer,'select save_asset($1,1)',[JSON.stringify({...asset,qty:10})]));await assert.rejects(()=>asUser(editor,'select set_member_role($1,$2)',[pending,'admin']));await assert.rejects(()=>asUser(editor,'update quotes set price_idr=9999'));});
test('optimistic concurrency rejects stale write; invalid value rolls back',async()=>{await asUser(editor,'select save_asset($1,1)',[JSON.stringify({...asset,qty:3})]);await assert.rejects(()=>asUser(editor,'select save_asset($1,1)',[JSON.stringify({...asset,qty:4})]));await assert.rejects(()=>asUser(editor,'select save_asset($1,2)',[JSON.stringify({...asset,manual_price:-1})]));assert.equal(Number((await asUser(viewer,'select qty from assets')).rows[0].qty),3)});
test('admin approval works; self-demotion blocked; blocked user loses read',async()=>{await asUser(admin,'select set_member_role($1,$2)',[pending,'viewer']);assert.equal((await asUser(pending,'select * from assets')).rows.length,1);await assert.rejects(()=>asUser(admin,'select set_member_role($1,$2)',[admin,'viewer']));await asUser(admin,'select set_member_role($1,$2)',[pending,'blocked']);assert.equal((await asUser(pending,'select * from assets')).rows.length,0);assert.equal((await asUser(pending,'select * from quotes')).rows.length,0)});
test('anon cannot read assets; members cannot run service-only functions',async()=>{await db.exec('set role anon');await assert.rejects(()=>db.query('select * from assets'));await assert.rejects(()=>db.query('select * from quotes'));await db.exec('reset role');await assert.rejects(()=>asUser(admin,'select claim_market_refresh(60)'));await assert.rejects(()=>asUser(viewer,"select allow_market_search('x')"));});
test('mapping change invalidates quote and audit is admin-only',async()=>{await asUser(editor,'select save_asset($1,2)',[JSON.stringify({...asset,provider:'coingecko',provider_id:'bitcoin'})]);assert.equal((await asUser(viewer,'select * from quotes')).rows.length,0);assert.equal((await asUser(viewer,'select * from audit_log')).rows.length,0);assert.ok((await asUser(admin,'select * from audit_log')).rows.length>0)});
test.after(()=>db.close());
